Feature/main
petD-ary/petDiary pull request #24
Opened 2023-11-15 07:08 UTC by juhee067

### PR 타입(하나 이상의 PR 타입을 선택해주세요)
- [ x] 기능 추가
- [ ] 기능 삭제
- [ ] 버그 수정
- [ ] 의존성, 환경 변수, 빌드 관련 코드 업데이트

### 반영 브랜치
ex) feature/main -> dev

### 변경 사항
main layout markup 적용

### 테스트 결과

2023-11-15 07:41 UTC, Dorabang requested changes
확인하고 주희가 머지 해주는 게 좋을 것 같아용!!!

2023-11-15 07:41 UTC, Dorabang commented on app/components/Input/SocialButton/index.tsx
>      </button>
오오옹ㅇ!!! 이게 더 좋은 것 같아!!!

2023-11-15 07:41 UTC, Dorabang commented on app/components/Main/PetInfo/PetImg.tsx
> +      <img className="h-56"></img>
<img/> 태그보다는 next/Image를 쓰는 게 최적화에 더 좋아서 나중에 작업할 때는 변경해주는 게 좋을 것 같아!!

외부 경로에서 받아오는 경우에는 크기가 무진장 커질텐데
1. 부모요소에 크기 설정, `className='relative'` 추가
2. <Image/> 태그에 `fill` 설정, `className='object-cover'` 추가
해주면 될거야([공식문서 참고](https://nextjs.org/docs/app/building-your-application/optimizing/images#fill-container))

2023-11-15 07:41 UTC, Dorabang commented on app/components/Main/Schedule/ScheduleList.tsx
> +    </div>
하위 컴포넌트가 이미 `<div>`로 감싸져있기 때문에 여기서도 `<div>`로 굳이 감쌀 필요없다고 생각합니다!
그리고 `return` 위에 가상 데이터 만들어서
```
const schedule = [{
id: 0,
data: '23',
day: '토요일',
...
}
]

return (
  {schedule && schedule.map(({id, date, day, detail}) =>
<ScheduleItem
        key={id}
        date={date}
        day={day}
        detail={
          <ScheduleItemDetail work={detail.work} location={detail.location} time={detail.time} />
        }
    />
)}
)
```
이런 식으로 해주면 나중에 작업할 때 편할 것 같아!!!

2023-11-15 07:41 UTC, Dorabang commented on app/components/SideMenu/SideMenu.tsx
> +        })}
map할 때 key 값을 index로 주면 key 값 역할을 잘 못할때가 있어서 차라리 `title`이나 `link`를 key 값으로 넣어주는 게 좋을 것 같아!([참고 문서](https://medium.com/sjk5766/react-%EB%B0%B0%EC%97%B4%EC%9D%98-index%EB%A5%BC-key%EB%A1%9C-%EC%93%B0%EB%A9%B4-%EC%95%88%EB%90%98%EB%8A%94-%EC%9D%B4%EC%9C%A0-3ce48b3a18fb))

2023-11-15 07:41 UTC, Dorabang commented on page에서
요상한 파일이 같이 올라왔어용~!~!~!

2023-11-17 05:45 UTC, juhee067 reviewed
수정했습니다.

2023-11-17 05:45 UTC, juhee067 commented on app/components/Main/Schedule/ScheduleList.tsx
> +    </div>
넵 이건 다시 정리해서 올리겠습니다.

2023-11-17 05:45 UTC, juhee067 commented on app/components/Main/PetInfo/PetImg.tsx
> +      <img className="h-56"></img>
확인 후 수정했습니다.

2023-11-17 05:51 UTC, Dorabang reviewed
PR 할 수 있게 해주세요,,,

2023-11-17 06:04 UTC, Dorabang approved these changes

2023-11-17 06:04 UTC, merged